### PR TITLE
add https_only, started from Firefox 76

### PR DESCRIPTION
**Pull request by dimon4ezzz**
i guess https_everywhere should be removed

### CODE REVIEW

**Comment by dimon4ezzz** [comment]
Please, add advanced description to `help_text` field

**Comment by allo-** [comment]
HTTPS everywhere switches to HTTPS when it is available.
This option shows a warning for unencrypted connections like for SSL errors.

This probably belongs to a profile like #50 (Paranoid) or #114 (Harden HTTPS).
I think I would not like to include it in the main profile, because it sounds like a good option, but (almost) breaks a lot at the current state of the web.

I still would like to allow the user to merge profiles, so he can use "default+harden https" to see the standard options and the options that break sites without https / with outdated encryption standards.

**Comment by Madis0** [comment]
For now this would belong to Paranoid, yes. I hoped that Firefox could include something like [HTTPZ](https://addons.mozilla.org/et/firefox/addon/httpz/), which would attempt HTTPS first but also fallback automatically when needed.

**Comment by allo-** [comment]
HTTPZ may be worth to be included as addon. I need to try it, but when it's lightweight enough it would be a nice security improvement.

**Review by Mickiie1 — APPROVED** [review]

**Comment by dimon4ezzz** [comment]
cannot be used after [Firefox 91](https://blog.mozilla.org/security/2021/08/10/firefox-91-introduces-https-by-default-in-private-browsing/), where HTTPS-First setting was introduced

**Pull request closed without merging**
